### ISSUE TITLE
_csv.Error: field larger than field limit

### ISSUE THREAD

**Issue by thnewlands** [visualcurrent/Notion-2-Obsidan#26]
Hi I tried running the script on my Notion export and got this error. Not sure what to make of it -- my Notion export is huge ~5gb so I'd imagine its a stress test.

```
(base) PS D:\Notion-2-Obsidan-master> python .\N2O.py
Traceback (most recent call last):
  File ".\N2O.py", line 90, in <module>
    mdTitle = N2Omodule.N2Ocsv(csvFile)
  File "D:\Notion-2-Obsidan-master\N2Omodule.py", line 98, in N2Ocsv
    for row in reader: # I don't know how this works but it does what I want
  File "C:\Users\USER\Anaconda3\lib\csv.py", line 111, in __next__
    self.fieldnames
  File "C:\Users\USER\Anaconda3\lib\csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: field larger than field limit (131072)
```

**Comment by thnewlands** [comment]
I removed the files I'd imported from Evernote into Notion and exported out and I was able to get it to run. Must have been a huge CSV from Notion importing Evernote that was too big for the CSV library. Not sure if there's a way around that or a diff csv lib that would handle huge csv's like that?
