### ISSUE TITLE
[Error]'PosixPath' object has no attribute 'seek'

### ISSUE THREAD

**Issue by rosuH** [visualcurrent/Notion-2-Obsidan#9]
Env:
- MacOS 10.14.6
- Python 3.6.1

After select `zip` file, the following error occurred:

```
objc[36412]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8dbd73f0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x117db4f50). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "N2O.py", line 22, in <module>
    notionsData = ZipFile(NotionZip, 'r')
  File "/Users/rosu/.pyenv/versions/3.6.1/lib/python3.6/zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "/Users/rosu/.pyenv/versions/3.6.1/lib/python3.6/zipfile.py", line 1164, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/Users/rosu/.pyenv/versions/3.6.1/lib/python3.6/zipfile.py", line 241, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'PosixPath' object has no attribute 'seek'
```

**Comment by rosuH** [comment]
Fixed by using Python `3.8.6`.
